//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaaS.Mailer.Templates.PdfSam.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Subjects {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Subjects() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SaaS.Mailer.Templates.PdfSam.App_GlobalResources.Subjects", typeof(Subjects).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account creation complete.
        /// </summary>
        public static string AccountCreationCompleteNotification {
            get {
                return ResourceManager.GetString("AccountCreationCompleteNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email change confirmation.
        /// </summary>
        public static string EmailChangeConfirmationNotification {
            get {
                return ResourceManager.GetString("EmailChangeConfirmationNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email has been successfully changed.
        /// </summary>
        public static string EmailChangeNotification {
            get {
                return ResourceManager.GetString("EmailChangeNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate your account.
        /// </summary>
        public static string EmailConfirmationNotification {
            get {
                return ResourceManager.GetString("EmailConfirmationNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge request verification email.
        /// </summary>
        public static string MergeConfirmationNotification {
            get {
                return ResourceManager.GetString("MergeConfirmationNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password change.
        /// </summary>
        public static string PasswordChangedNotification {
            get {
                return ResourceManager.GetString("PasswordChangedNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitation to use [product name].
        /// </summary>
        public static string ProductAssignedNotificationCreatePassword {
            get {
                return ResourceManager.GetString("ProductAssignedNotificationCreatePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product expired.
        /// </summary>
        public static string ProductRenewalOffNotification {
            get {
                return ResourceManager.GetString("ProductRenewalOffNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [product name] Renewal is off.
        /// </summary>
        public static string ProductSuspendNotification {
            get {
                return ResourceManager.GetString("ProductSuspendNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [product name] is unassigned.
        /// </summary>
        public static string ProductUnassignedNotification {
            get {
                return ResourceManager.GetString("ProductUnassignedNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password reset.
        /// </summary>
        public static string RecoverPasswordNotification {
            get {
                return ResourceManager.GetString("RecoverPasswordNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your product key has been sent.
        /// </summary>
        public static string WelcomeFreeProductNotification {
            get {
                return ResourceManager.GetString("WelcomeFreeProductNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for purchasing [product name].
        /// </summary>
        public static string WelcomePurchaseNotification {
            get {
                return ResourceManager.GetString("WelcomePurchaseNotification", resourceCulture);
            }
        }
    }
}
