(function () {
    'use strict';

    angular
        .module('app.services')
        .factory('$dict', dict);

    dict.$inject = [];

    function dict() {

        var service = {};


        Object.defineProperties(service, {

            productsOfInterest: {
                get: function () {
                    return [{ name: 'Soda PDF Premium' },
                            { name: 'Soda PDF Business' },
                            { name: 'Soda PDF 9 Enterprise' }];
                }
            },

            jobRoles: {
                get: function () {
                    return [
                        { name: 'Accounting' },
                        { name: 'Administrative' },
                        { name: 'Communications' },
                        { name: 'Creative' },
                        { name: 'Customer Service' },
                        { name: 'Education' },
                        { name: 'Engineering' },
                        { name: 'Freelance' },
                        { name: 'Health Care Provider' },
                        { name: 'Human Resources' },
                        { name: 'IT' },
                        { name: 'Legal' },
                        { name: 'Marketing' },
                        { name: 'Operations' },
                        { name: 'Product Management' },
                        { name: 'Public Relations' },
                        { name: 'Quality Assurance' },
                        { name: 'Sales' },
                        { name: 'Social Media' },
                        { name: 'Student' },
                        { name: 'Teacher' }];

                }
            },

            industries: {
                get: function () {
                    return [{ name: 'Banking' },
                            { name: 'eCommerce' },
                            { name: 'Education' },
                            { name: 'Engineering & Construction' },
                            { name: 'Financial Services' },
                            { name: 'Travel & Hospitality' },
                            { name: 'Healthcare' },
                            { name: 'Insurance' },
                            { name: 'IT Services' },
                            { name: 'Legal' },
                            { name: 'Manufacturing' },
                            { name: 'Non-Profit' },
                            { name: 'Pharmaceuticals' },
                            { name: 'Real Estate' },
                            { name: 'Retail' },
                            { name: 'Software - Reseller' },
                            { name: 'Software - Developer' },
                            { name: 'Technology' },
                            { name: 'Telecommunications' },
                            { name: 'Transportation & Shipping' },
                            { name: 'Other' }];
                }
            },

            products: {
                get: function () {

                    return [{ name: 'Soda PDF Desktop' },
                            { name: 'Soda PDF Online' },
                            { name: 'Soda PDF 8' },
                            { name: 'Soda PDF 7' },
                            { name: 'Soda PDF 6' },
                            { name: 'Soda PDF 5' },
                            { name: 'Soda PDF 2012' },
                            { name: 'Soda PDF 3D Reader' },
                            { name: 'Soda PDF MAC' }];
                }
            },
            languages: {
                get: function () {

                    return [{ name: 'Afar', iso2: 'aa' }, { name: 'Abkhazian', iso2: 'ab' }, { name: 'Avestan', iso2: 'ae' }, { name: 'Afrikaans', iso2: 'af' }, { name: 'Akan', iso2: 'ak' }, { name: 'Amharic', iso2: 'am' }, { name: 'Aragonese', iso2: 'an' }, { name: 'Arabic', iso2: 'ar' }, { name: 'Assamese', iso2: 'as' }, { name: 'Avaric', iso2: 'av' }, { name: 'Aymara', iso2: 'ay' }, { name: 'Azerbaijani', iso2: 'az' }, { name: 'Bashkir', iso2: 'ba' }, { name: 'Belarusian', iso2: 'be' }, { name: 'Bulgarian', iso2: 'bg' }, { name: 'Bihari', iso2: 'bh' }, { name: 'Bislama', iso2: 'bi' }, { name: 'Bambara', iso2: 'bm' }, { name: 'Bengali', iso2: 'bn' }, { name: 'Tibetan', iso2: 'bo' }, { name: 'Breton', iso2: 'br' }, { name: 'Bosnian', iso2: 'bs' }, { name: 'Catalan', iso2: 'ca' }, { name: 'Chechen', iso2: 'ce' }, { name: 'Chamorro', iso2: 'ch' }, { name: 'Corsican', iso2: 'co' }, { name: 'Cree', iso2: 'cr' }, { name: 'Czech', iso2: 'cs' }, { name: 'Church', iso2: 'cu' }, { name: 'Chuvash', iso2: 'cv' }, { name: 'Welsh', iso2: 'cy' }, { name: 'Danish', iso2: 'da' }, { name: 'German', iso2: 'de' }, { name: 'Dhivehi', iso2: 'dv' },
                        { name: 'Dzongkha', iso2: 'dz' }, { name: 'Ewe', iso2: 'ee' }, { name: 'Modern Greek (1453-)', iso2: 'el' }, { name: 'English', iso2: 'en' }, { name: 'Esperanto', iso2: 'eo' }, { name: 'Spanish', iso2: 'es' }, { name: 'Estonian', iso2: 'et' }, { name: 'Basque', iso2: 'eu' }, { name: 'Persian', iso2: 'fa' }, { name: 'Fulah', iso2: 'ff' }, { name: 'Finnish', iso2: 'fi' }, { name: 'Fijian', iso2: 'fj' }, { name: 'Faroese', iso2: 'fo' }, { name: 'French', iso2: 'fr' }, { name: 'Western Frisian', iso2: 'fy' }, { name: 'Irish', iso2: 'ga' }, { name: 'Scottish Gaelic', iso2: 'gd' }, { name: 'Galician', iso2: 'gl' }, { name: 'Guarani', iso2: 'gn' }, { name: 'Gujarati', iso2: 'gu' }, { name: 'Manx', iso2: 'gv' }, { name: 'Hausa', iso2: 'ha' }, { name: 'Hebrew', iso2: 'he' }, { name: 'Hindi', iso2: 'hi' }, { name: 'Hiri Motu', iso2: 'ho' }, { name: 'Croatian', iso2: 'hr' }, { name: 'Haitian', iso2: 'ht' }, { name: 'Hungarian', iso2: 'hu' }, { name: 'Armenian', iso2: 'hy' }, { name: 'Herero', iso2: 'hz' }, { name: 'Interlingua', iso2: 'ia' }, { name: 'Indonesian', iso2: 'id' },
                        { name: 'Interlingue', iso2: 'ie' }, { name: 'Igbo', iso2: 'ig' }, { name: 'Sichuan Yi', iso2: 'ii' }, { name: 'Inupiaq', iso2: 'ik' }, { name: 'Ido', iso2: 'io' }, { name: 'Icelandic', iso2: 'is' }, { name: 'Italian', iso2: 'it' }, { name: 'Inuktitut', iso2: 'iu' }, { name: 'Japanese', iso2: 'ja' }, { name: 'Javanese', iso2: 'jv' }, { name: 'Georgian', iso2: 'ka' }, { name: 'Kongo', iso2: 'kg' }, { name: 'Kikuyu', iso2: 'ki' }, { name: 'Kuanyama', iso2: 'kj' }, { name: 'Kazakh', iso2: 'kk' }, { name: 'Kalaallisut', iso2: 'kl' }, { name: 'Central Khmer', iso2: 'km' }, { name: 'Kannada', iso2: 'kn' }, { name: 'Korean', iso2: 'ko' }, { name: 'Kanuri', iso2: 'kr' }, { name: 'Kashmiri', iso2: 'ks' }, { name: 'Kurdish', iso2: 'ku' }, { name: 'Komi', iso2: 'kv' }, { name: 'Cornish', iso2: 'kw' }, { name: 'Kirghiz', iso2: 'ky' }, { name: 'Latin', iso2: 'la' }, { name: 'Luxembourgish', iso2: 'lb' }, { name: 'Ganda', iso2: 'lg' }, { name: 'Limburgan', iso2: 'li' }, { name: 'Lingala', iso2: 'ln' }, { name: 'Lao', iso2: 'lo' }, { name: 'Lithuanian', iso2: 'lt' }, { name: 'Luba-Katanga', iso2: 'lu' }, { name: 'Latvian', iso2: 'lv' },
                        { name: 'Malagasy', iso2: 'mg' }, { name: 'Marshallese', iso2: 'mh' }, { name: 'Maori', iso2: 'mi' }, { name: 'Macedonian', iso2: 'mk' }, { name: 'Malayalam', iso2: 'ml' }, { name: 'Mongolian', iso2: 'mn' }, { name: 'Marathi', iso2: 'mr' }, { name: 'Malay (macrolanguage)', iso2: 'ms' }, { name: 'Maltese', iso2: 'mt' }, { name: 'Burmese', iso2: 'my' }, { name: 'Nauru', iso2: 'na' }, { name: 'Norwegian Bokmål', iso2: 'nb' }, { name: 'North Ndebele', iso2: 'nd' }, { name: 'Nepali (macrolanguage)', iso2: 'ne' }, { name: 'Ndonga', iso2: 'ng' }, { name: 'Dutch', iso2: 'nl' }, { name: 'Norwegian Nynorsk', iso2: 'nn' }, { name: 'Norwegian', iso2: 'no' }, { name: 'South Ndebele', iso2: 'nr' }, { name: 'Navajo', iso2: 'nv' }, { name: 'Nyanja', iso2: 'ny' }, { name: 'Occitan (post 1500)', iso2: 'oc' }, { name: 'Ojibwa', iso2: 'oj' }, { name: 'Oromo', iso2: 'om' }, { name: 'Oriya (macrolanguage)', iso2: 'or' }, { name: 'Ossetian', iso2: 'os' }, { name: 'Panjabi', iso2: 'pa' }, { name: 'NEWLANGUAGE02', iso2: 'pd' }, { name: 'Pali', iso2: 'pi' }, { name: 'Polish', iso2: 'pl' }, { name: 'Pushto', iso2: 'ps' }, { name: 'Portuguese', iso2: 'pt' },
                        { name: 'Quechua', iso2: 'qu' }, { name: 'Romansh', iso2: 'rm' }, { name: 'Rundi', iso2: 'rn' }, { name: 'Romanian', iso2: 'ro' }, { name: 'Russian', iso2: 'ru' }, { name: 'Kinyarwanda', iso2: 'rw' }, { name: 'Sanskrit', iso2: 'sa' }, { name: 'Sardinian', iso2: 'sc' }, { name: 'Sindhi', iso2: 'sd' }, { name: 'Northern', iso2: 'se' }, { name: 'Sango', iso2: 'sg' }, { name: 'Serbo-Croatian', iso2: 'sh' }, { name: 'Sinhala', iso2: 'si' }, { name: 'Slovak', iso2: 'sk' }, { name: 'Slovenian', iso2: 'sl' }, { name: 'Samoan', iso2: 'sm' }, { name: 'Shona', iso2: 'sn' }, { name: 'Somali', iso2: 'so' }, { name: 'Albanian', iso2: 'sq' }, { name: 'Serbian', iso2: 'sr' }, { name: 'Swati', iso2: 'ss' }, { name: 'Southern Sotho', iso2: 'st' }, { name: 'Sundanese', iso2: 'su' }, { name: 'Swedish', iso2: 'sv' }, { name: 'Swahili (macrolanguage)', iso2: 'sw' }, { name: 'Tamil', iso2: 'ta' }, { name: 'Telugu', iso2: 'te' }, { name: 'Tajik', iso2: 'tg' }, { name: 'Thai', iso2: 'th' }, { name: 'Tigrinya', iso2: 'ti' }, { name: 'Turkmen', iso2: 'tk' }, { name: 'Tagalog', iso2: 'tl' }, { name: 'Tswana', iso2: 'tn' }, { name: 'Tonga (Tonga Islands)', iso2: 'to' },
                        { name: 'Turkish', iso2: 'tr' }, { name: 'Tsonga', iso2: 'ts' }, { name: 'Tatar', iso2: 'tt' }, { name: 'Twi', iso2: 'tw' }, { name: 'Tahitian', iso2: 'ty' }, { name: 'Uighur', iso2: 'ug' }, { name: 'Ukrainian', iso2: 'uk' }, { name: 'Urdu', iso2: 'ur' }, { name: 'Uzbek', iso2: 'uz' }, { name: 'Venda', iso2: 've' }, { name: 'Vietnamese', iso2: 'vi' }, { name: 'Volapük', iso2: 'vo' }, { name: 'Walloon', iso2: 'wa' }, { name: 'Wolof', iso2: 'wo' }, { name: 'Xhosa', iso2: 'xh' }, { name: 'Yiddish', iso2: 'yi' }, { name: 'Yoruba', iso2: 'yo' }, { name: 'Zhuang', iso2: 'za' }, { name: 'Chinese', iso2: 'zh' }, { name: 'Zulu', iso2: 'zu' }];
                }
            },
            currencies: {
                get: function () {

                    return [{ name: 'Afghani', iso3: 'AFN' }, { name: 'Algerian Dinar', iso3: 'DZD' }, { name: 'Argentine Peso', iso3: 'ARS' }, { name: 'Armenian Dram', iso3: 'AMD' }, { name: 'Aruban Guilder', iso3: 'AWG' }, { name: 'Australian Dollar', iso3: 'AUD' }, { name: 'Azerbaijanian Manat', iso3: 'AZN' }, { name: 'Bahamian Dollar', iso3: 'BSD' }, { name: 'Bahraini Dinar', iso3: 'BHD' }, { name: 'Baht', iso3: 'THB' }, { name: 'Balboa', iso3: 'PAB' }, { name: 'Bangladeshi Taka', iso3: 'BDT' }, { name: 'Barbados Dollar', iso3: 'BBD' }, { name: 'Belarusian Ruble', iso3: 'BYR' }, { name: 'Belarusian rubles', iso3: 'BYN' }, { name: 'Belize Dollar', iso3: 'BZD' }, { name: 'Bermudian Dollar', iso3: 'BMD' }, { name: 'Boliviano', iso3: 'BOB' }, { name: 'Brazilian Real', iso3: 'BRL' }, { name: 'Brunei Dollar', iso3: 'BND' }, { name: 'Bulgarian Lev', iso3: 'BGN' }, { name: 'Burundian Franc', iso3: 'BIF' }, { name: 'Canadian Dollar', iso3: 'CAD' }, { name: 'Cape Verde Escudo', iso3: 'CVE' }, { name: 'Cayman Islands Dollar', iso3: 'KYD' }, { name: 'Cedi', iso3: 'GHS' }, { name: 'CFA Franc BCEAO', iso3: 'XOF' }, { name: 'CFA Franc BEAC', iso3: 'XAF' }, { name: 'CFP Franc', iso3: 'XPF' },
                        { name: 'Chilean Peso', iso3: 'CLP' }, { name: 'Chinese Yuan', iso3: 'CNY' }, { name: 'Colombian Peso', iso3: 'COP' }, { name: 'Comoro Franc', iso3: 'KMF' }, { name: 'Congolese Franc', iso3: 'CDF' }, { name: 'Convertible Marks', iso3: 'BAM' }, { name: 'Cordoba Oro', iso3: 'NIO' }, { name: 'Costa Rican Colon', iso3: 'CRC' }, { name: 'Croatian Kuna', iso3: 'HRK' }, { name: 'Cuba Convertible Pesos', iso3: 'CUC' }, { name: 'Cuban Peso', iso3: 'CUP' }, { name: 'Cyprus Pounds', iso3: 'CYP' }, { name: 'Czech Koruna', iso3: 'CZK' }, { name: 'Dalasi', iso3: 'GMD' }, { name: 'Danish Krone', iso3: 'DKK' }, { name: 'Denar', iso3: 'MKD' }, { name: 'Djibouti Franc', iso3: 'DJF' }, { name: 'Dobra', iso3: 'STD' }, { name: 'Dominican Peso', iso3: 'DOP' }, { name: 'East Caribbean Dollar', iso3: 'XCD' }, { name: 'Egyptian Pound', iso3: 'EGP' }, { name: 'El Salvador Colones', iso3: 'SVC' }, { name: 'Ethiopian Birr', iso3: 'ETB' }, { name: 'Euro', iso3: 'EUR' }, { name: 'Falkland Islands Pound', iso3: 'FKP' }, { name: 'Fiji Dollar', iso3: 'FJD' }, { name: 'Forint', iso3: 'HUF' }, { name: 'Ghana Cedis', iso3: 'GHC' }, { name: 'Gibraltar Pound', iso3: 'GIP' },
                        { name: 'Gold Ounces', iso3: 'XAU' }, { name: 'Guarani', iso3: 'PYG' }, { name: 'Guernsey Pounds', iso3: 'GGP' }, { name: 'Guinea Franc', iso3: 'GNF' }, { name: 'Guyana Dollar', iso3: 'GYD' }, { name: 'Haiti Gourde', iso3: 'HTG' }, { name: 'Hong Kong Dollar', iso3: 'HKD' }, { name: 'Hryvnia', iso3: 'UAH' }, { name: 'Iceland Krona', iso3: 'ISK' }, { name: 'Indian Rupee', iso3: 'INR' }, { name: 'International Monetary Fund Special Drawing Rights', iso3: 'XDR' }, { name: 'Iranian Rial', iso3: 'IRR' }, { name: 'Iraqi Dinar', iso3: 'IQD' }, { name: 'Isle of Man Pounds', iso3: 'IMP' }, { name: 'Israeli New Sheqel', iso3: 'ILS' }, { name: 'Jamaican Dollar', iso3: 'JMD' }, { name: 'Japanese Yen', iso3: 'JPY' }, { name: 'Jersey Pounds', iso3: 'JEP' }, { name: 'Jordanian Dinar', iso3: 'JOD' }, { name: 'Kenyan Shilling', iso3: 'KES' }, { name: 'Kina', iso3: 'PGK' }, { name: 'Kip', iso3: 'LAK' }, { name: 'Kroon', iso3: 'EEK' }, { name: 'Kuwaiti Dinar', iso3: 'KWD' }, { name: 'Kwacha', iso3: 'MWK' }, { name: 'Kwacha', iso3: 'ZMK' }, { name: 'Kwanza', iso3: 'AOA' }, { name: 'Kyat', iso3: 'MMK' }, { name: 'Lari', iso3: 'GEL' }, { name: 'Latvian Lats', iso3: 'LVL' },
                        { name: 'Lebanese Pound', iso3: 'LBP' }, { name: 'Lek', iso3: 'ALL' }, { name: 'Lempira', iso3: 'HNL' }, { name: 'Leone', iso3: 'SLL' }, { name: 'Lesotho Loti', iso3: 'LSL' }, { name: 'Liberian Dollar', iso3: 'LRD' }, { name: 'Libyan Dinar', iso3: 'LYD' }, { name: 'Lilangeni', iso3: 'SZL' }, { name: 'Lithuanian Litas', iso3: 'LTL' }, { name: 'Malagasy Ariary', iso3: 'MGA' }, { name: 'Malaysian Ringgit', iso3: 'MYR' }, { name: 'Malta Liri', iso3: 'MTL' }, { name: 'Manat', iso3: 'TMT' }, { name: 'Mauritius Rupee', iso3: 'MUR' }, { name: 'Metical', iso3: 'MZN' }, { name: 'Mexican Peso', iso3: 'MXN' }, { name: 'Moldovan Leu', iso3: 'MDL' }, { name: 'Moroccan Dirham', iso3: 'MAD' }, { name: 'Naira', iso3: 'NGN' }, { name: 'Nakfa', iso3: 'ERN' }, { name: 'Namibian Dollar', iso3: 'NAD' }, { name: 'Nepalese Rupee', iso3: 'NPR' }, { name: 'Netherlands Antillean Guilder', iso3: 'ANG' }, { name: 'New Taiwan Dollar', iso3: 'TWD' }, { name: 'New Zealand Dollar', iso3: 'NZD' }, { name: 'Ngultrum', iso3: 'BTN' }, { name: 'North Korean Won', iso3: 'KPW' }, { name: 'Norwegian Krone', iso3: 'NOK' }, { name: 'Nuevo Sol', iso3: 'PEN' }, { name: 'Ouguiya', iso3: 'MRO' },
                        { name: 'Pa\'anga', iso3: 'TOP' }, { name: 'Pakistan Rupee', iso3: 'PKR' }, { name: 'Palladium Ounces', iso3: 'XPD' }, { name: 'Pataca', iso3: 'MOP' }, { name: 'Peso Uruguayo', iso3: 'UYU' }, { name: 'Philippine Peso', iso3: 'PHP' }, { name: 'Platinum Ounces', iso3: 'XPT' }, { name: 'Pound Sterling', iso3: 'GBP' }, { name: 'Pula', iso3: 'BWP' }, { name: 'Qatari Rial', iso3: 'QAR' }, { name: 'Quetzal', iso3: 'GTQ' }, { name: 'Rial Omani', iso3: 'OMR' }, { name: 'Riel', iso3: 'KHR' }, { name: 'Romanian New Leu', iso3: 'RON' }, { name: 'Rufiyaa', iso3: 'MVR' }, { name: 'Rupiah', iso3: 'IDR' }, { name: 'Russian Rouble', iso3: 'RUB' }, { name: 'Rwanda Franc', iso3: 'RWF' }, { name: 'Saint Helena Pound', iso3: 'SHP' }, { name: 'Samoan Tala', iso3: 'WST' }, { name: 'Saudi Riyal', iso3: 'SAR' }, { name: 'Seborga Luigini', iso3: 'SPL' }, { name: 'Serbian Dinar', iso3: 'RSD' }, { name: 'Seychelles Rupee', iso3: 'SCR' }, { name: 'Silver Ounces', iso3: 'XAG' }, { name: 'Singapore Dollar', iso3: 'SGD' }, { name: 'Slovakia Koruny', iso3: 'SKK' }, { name: 'Solomon Islands Dollar', iso3: 'SBD' }, { name: 'Som', iso3: 'KGS' }, { name: 'Somali Shilling', iso3: 'SOS' },
                        { name: 'Somoni', iso3: 'TJS' }, { name: 'South African Rand', iso3: 'ZWL' }, { name: 'South African Rand', iso3: 'ZAR' }, { name: 'South Korean Won', iso3: 'KRW' }, { name: 'South Sudanese Pound', iso3: 'SSP' }, { name: 'Sri Lanka Rupee', iso3: 'LKR' }, { name: 'Sudan Dinars', iso3: 'SDD' }, { name: 'Sudanese Pound', iso3: 'SDG' }, { name: 'Surinam Dollar', iso3: 'SRD' }, { name: 'Swedish Krona/Kronor', iso3: 'SEK' }, { name: 'Swiss Franc', iso3: 'CHF' }, { name: 'Syrian Pound', iso3: 'SYP' }, { name: 'Tanzanian Shilling', iso3: 'TZS' }, { name: 'Tenge', iso3: 'KZT' }, { name: 'Trinidad and Tobago Dollar', iso3: 'TTD' }, { name: 'Tugrik', iso3: 'MNT' }, { name: 'Tunisian Dinar', iso3: 'TND' }, { name: 'Turkish Lira', iso3: 'TRY' }, { name: 'Turkmenistan Manats', iso3: 'TMM' }, { name: 'Tuvalu Dollars', iso3: 'TVD' }, { name: 'Uganda Shilling', iso3: 'UGX' }, { name: 'United Arab Emirates Dirham', iso3: 'AED' }, { name: 'US Dollar', iso3: 'USD' }, { name: 'Uzbekistan Som', iso3: 'UZS' }, { name: 'Vatu', iso3: 'VUV' }, { name: 'Venezuela Bolivares', iso3: 'VEB' }, { name: 'Venezuelan Bolivar Fuerte', iso3: 'VEF' }, { name: 'Vietnamese ??ng', iso3: 'VND' },
                        { name: 'Yemeni Rial', iso3: 'YER' }, { name: 'Zimbabwe Dollars', iso3: 'ZWD' }, { name: 'Zloty', iso3: 'PLN' }];
                }
            },
            countries: {
                get: function () {

                    return [{ name: 'Abkhazia', iso2: 'AB' }, { name: 'Andorra', iso2: 'AD' }, { name: 'United Arab Emirates', iso2: 'AE' }, { name: 'Afghanistan', iso2: 'AF' }, { name: 'Antigua and Barbuda', iso2: 'AG' }, { name: 'Anguilla', iso2: 'AI' }, { name: 'Albania', iso2: 'AL' }, { name: 'Armenia', iso2: 'AM' }, { name: 'Netherlands Antilles', iso2: 'AN' }, { name: 'Angola', iso2: 'AO' }, { name: 'Antarctica', iso2: 'AQ' }, { name: 'Argentina', iso2: 'AR' }, { name: 'American Samoa', iso2: 'AS' }, { name: 'Austria', iso2: 'AT' }, { name: 'Australia', iso2: 'AU' }, { name: 'Aruba', iso2: 'AW' }, { name: 'Åland Islands', iso2: 'AX' }, { name: 'Azerbaijan', iso2: 'AZ' }, { name: 'Bosnia and Herzegowina', iso2: 'BA' }, { name: 'Barbados', iso2: 'BB' }, { name: 'Bangladesh', iso2: 'BD' }, { name: 'Belgium', iso2: 'BE' }, { name: 'Burkina Faso', iso2: 'BF' }, { name: 'Bulgaria', iso2: 'BG' }, { name: 'Bahrain', iso2: 'BH' }, { name: 'Burundi', iso2: 'BI' }, { name: 'Benin', iso2: 'BJ' }, { name: 'Saint Barthélemy', iso2: 'BL' }, { name: 'Bermuda', iso2: 'BM' }, { name: 'Brunei Darussalam', iso2: 'BN' }, { name: 'Bolivia', iso2: 'BO' },
                        { name: 'Bonaire, Sint Eustatius and Saba', iso2: 'BQ' }, { name: 'Brazil', iso2: 'BR' }, { name: 'Bahamas', iso2: 'BS' }, { name: 'Bhutan', iso2: 'BT' }, { name: 'Bouvet Island', iso2: 'BV' }, { name: 'Botswana', iso2: 'BW' }, { name: 'Belarus', iso2: 'BY' }, { name: 'Belize', iso2: 'BZ' }, { name: 'Canada', iso2: 'CA' }, { name: 'Cocos (keeling) Islands', iso2: 'CC' }, { name: 'Congo - Democratic Rep', iso2: 'CD' }, { name: 'Central African Republic', iso2: 'CF' }, { name: 'Congo', iso2: 'CG' }, { name: 'Switzerland', iso2: 'CH' }, { name: 'Cote Ivoire', iso2: 'CI' }, { name: 'Cook Islands', iso2: 'CK' }, { name: 'Chile', iso2: 'CL' }, { name: 'Cameroon', iso2: 'CM' }, { name: 'China', iso2: 'CN' }, { name: 'Colombia', iso2: 'CO' }, { name: 'Costa Rica', iso2: 'CR' }, { name: 'Cuba', iso2: 'CU' }, { name: 'Cape Verde', iso2: 'CV' }, { name: 'Cura', iso2: 'CW' }, { name: 'Christmas Island', iso2: 'CX' }, { name: 'Cyprus', iso2: 'CY' }, { name: 'Czech Republic', iso2: 'CZ' }, { name: 'Deutschland', iso2: 'DE' }, { name: 'Djibouti', iso2: 'DJ' }, { name: 'Denmark', iso2: 'DK' }, { name: 'Dominica', iso2: 'DM' },
                        { name: 'Dominican Republic', iso2: 'DO' }, { name: 'Algeria', iso2: 'DZ' }, { name: 'Ecuador', iso2: 'EC' }, { name: 'Estonia', iso2: 'EE' }, { name: 'Egypt', iso2: 'EG' }, { name: 'Western Sahara', iso2: 'EH' }, { name: 'Eritrea', iso2: 'ER' }, { name: 'España', iso2: 'ES' }, { name: 'Ethiopia', iso2: 'ET' }, { name: 'Finland', iso2: 'FI' }, { name: 'Fiji', iso2: 'FJ' }, { name: 'Falkland Islands', iso2: 'FK' }, { name: 'Micronesia', iso2: 'FM' }, { name: 'Faroe Islands', iso2: 'FO' }, { name: 'France', iso2: 'FR' }, { name: 'Gabon', iso2: 'GA' }, { name: 'United Kingdom', iso2: 'GB' }, { name: 'Grenada', iso2: 'GD' }, { name: 'Georgia', iso2: 'GE' }, { name: 'Guyane française ', iso2: 'GF' }, { name: 'Guernsey', iso2: 'GG' }, { name: 'Ghana', iso2: 'GH' }, { name: 'Gibraltar', iso2: 'GI' }, { name: 'Greenland', iso2: 'GL' }, { name: 'Gambia', iso2: 'GM' }, { name: 'Guinea', iso2: 'GN' }, { name: 'Guadeloupe', iso2: 'GP' }, { name: 'Equatorial Guinea', iso2: 'GQ' }, { name: 'Greece', iso2: 'GR' }, { name: 'South Georgia', iso2: 'GS' }, { name: 'Guatemala', iso2: 'GT' }, { name: 'Guam', iso2: 'GU' },
                        { name: 'Guinea-Bissau', iso2: 'GW' }, { name: 'Guyana', iso2: 'GY' }, { name: 'Hong Kong', iso2: 'HK' }, { name: 'Heard and Mcdonald Islands', iso2: 'HM' }, { name: 'Honduras', iso2: 'HN' }, { name: 'Croatia', iso2: 'HR' }, { name: 'Haiti', iso2: 'HT' }, { name: 'Hungary', iso2: 'HU' }, { name: 'Indonesia', iso2: 'ID' }, { name: 'Ireland', iso2: 'IE' }, { name: 'Israel', iso2: 'IL' }, { name: 'Isle of Man', iso2: 'IM' }, { name: 'India', iso2: 'IN' }, { name: 'British Indian Ocean Territory', iso2: 'IO' }, { name: 'Iraq', iso2: 'IQ' }, { name: 'Iran', iso2: 'IR' }, { name: 'Iceland', iso2: 'IS' }, { name: 'Italy', iso2: 'IT' }, { name: 'Jersey', iso2: 'JE' }, { name: 'Jamaica', iso2: 'JM' }, { name: 'Jordan', iso2: 'JO' }, { name: 'Japan', iso2: 'JP' }, { name: 'Kenya', iso2: 'KE' }, { name: 'Kyrgyzstan', iso2: 'KG' }, { name: 'Cambodia', iso2: 'KH' }, { name: 'Kiribati', iso2: 'KI' }, { name: 'Comoros', iso2: 'KM' }, { name: 'Saint Kitts and Nevis', iso2: 'KN' }, { name: 'Korea - North', iso2: 'KP' }, { name: 'Korea - South', iso2: 'KR' }, { name: 'Kuwait', iso2: 'KW' }, { name: 'Cayman Islands', iso2: 'KY' },
                        { name: 'Kazakhstan', iso2: 'KZ' }, { name: 'Lao', iso2: 'LA' }, { name: 'Lebanon', iso2: 'LB' }, { name: 'Saint Lucia', iso2: 'LC' }, { name: 'Liechtenstein', iso2: 'LI' }, { name: 'Sri Lanka', iso2: 'LK' }, { name: 'Liberia', iso2: 'LR' }, { name: 'Lesotho', iso2: 'LS' }, { name: 'Lithuania', iso2: 'LT' }, { name: 'Luxembourg', iso2: 'LU' }, { name: 'Latvia', iso2: 'LV' }, { name: 'Libyan Arab Jamahiriya', iso2: 'LY' }, { name: 'Morocco', iso2: 'MA' }, { name: 'Monaco', iso2: 'MC' }, { name: 'Moldova', iso2: 'MD' }, { name: 'Montenegro', iso2: 'ME' }, { name: 'Saint Martin', iso2: 'MF' }, { name: 'Madagascar', iso2: 'MG' }, { name: 'Marshall Islands', iso2: 'MH' }, { name: 'Macedonia', iso2: 'MK' }, { name: 'Mali', iso2: 'ML' }, { name: 'Myanmar', iso2: 'MM' }, { name: 'Mongolia', iso2: 'MN' }, { name: 'Macau', iso2: 'MO' }, { name: 'Northern Mariana Islands', iso2: 'MP' }, { name: 'Martinique', iso2: 'MQ' }, { name: 'Mauritania', iso2: 'MR' }, { name: 'Montserrat', iso2: 'MS' }, { name: 'Malta', iso2: 'MT' }, { name: 'Mauritius', iso2: 'MU' }, { name: 'Maldives', iso2: 'MV' }, { name: 'Malawi', iso2: 'MW' },
                        { name: 'Mexico', iso2: 'MX' }, { name: 'Malaysia', iso2: 'MY' }, { name: 'Mozambique', iso2: 'MZ' }, { name: 'Namibia', iso2: 'NA' }, { name: 'New Caledonia', iso2: 'NC' }, { name: 'Niger', iso2: 'NE' }, { name: 'Norfolk Island', iso2: 'NF' }, { name: 'Nigeria', iso2: 'NG' }, { name: 'Nicaragua', iso2: 'NI' }, { name: 'Netherlands', iso2: 'NL' }, { name: 'Norway', iso2: 'NO' }, { name: 'Nepal', iso2: 'NP' }, { name: 'Nauru', iso2: 'NR' }, { name: 'Niue', iso2: 'NU' }, { name: 'New Zealand', iso2: 'NZ' }, { name: 'Oman', iso2: 'OM' }, { name: 'South Ossetia', iso2: 'OS' }, { name: 'Panama', iso2: 'PA' }, { name: 'Peru', iso2: 'PE' }, { name: 'Polynésie française', iso2: 'PF' }, { name: 'Papua New Guinea', iso2: 'PG' }, { name: 'Philippines', iso2: 'PH' }, { name: 'Pakistan', iso2: 'PK' }, { name: 'Poland', iso2: 'PL' }, { name: 'St. Pierre and Miquelon', iso2: 'PM' }, { name: 'Pitcairn', iso2: 'PN' }, { name: 'Puerto Rico', iso2: 'PR' }, { name: 'Palestinian territories', iso2: 'PS' }, { name: 'Portugal', iso2: 'PT' }, { name: 'Palau', iso2: 'PW' }, { name: 'Paraguay', iso2: 'PY' }, { name: 'Qatar', iso2: 'QA' },
                        { name: 'Reunion', iso2: 'RE' }, { name: 'Romania', iso2: 'RO' }, { name: 'Serbia', iso2: 'RS' }, { name: 'Russian Federation', iso2: 'RU' }, { name: 'Rwanda', iso2: 'RW' }, { name: 'Saudi Arabia', iso2: 'SA' }, { name: 'Solomon Islands', iso2: 'SB' }, { name: 'Seychelles', iso2: 'SC' }, { name: 'Sudan', iso2: 'SD' }, { name: 'Sweden', iso2: 'SE' }, { name: 'Singapore', iso2: 'SG' }, { name: 'St. Helena', iso2: 'SH' }, { name: 'Slovenia', iso2: 'SI' }, { name: 'Svalbard Islands', iso2: 'SJ' }, { name: 'Slovakia', iso2: 'SK' }, { name: 'Sierra Leone', iso2: 'SL' }, { name: 'San Marino', iso2: 'SM' }, { name: 'Senegal', iso2: 'SN' }, { name: 'Somalia', iso2: 'SO' }, { name: 'Suriname', iso2: 'SR' }, { name: 'South Sudan', iso2: 'SS' }, { name: 'Sao Tome', iso2: 'ST' }, { name: 'El Salvador', iso2: 'SV' }, { name: 'Sint Maarten', iso2: 'SX' }, { name: 'Syrian Arab Republic', iso2: 'SY' }, { name: 'Swaziland', iso2: 'SZ' }, { name: 'Turks and Caicos Islands', iso2: 'TC' }, { name: 'Chad', iso2: 'TD' }, { name: 'French Southern Territories', iso2: 'TF' }, { name: 'Togo', iso2: 'TG' }, { name: 'Thailand', iso2: 'TH' },
                        { name: 'Tajikistan', iso2: 'TJ' }, { name: 'Tokelau', iso2: 'TK' }, { name: 'East Timor', iso2: 'TL' }, { name: 'Turkmenistan', iso2: 'TM' }, { name: 'Tunisia', iso2: 'TN' }, { name: 'Tonga', iso2: 'TO' }, { name: 'Turkey', iso2: 'TR' }, { name: 'Trinidad and Tobago', iso2: 'TT' }, { name: 'Tuvalu', iso2: 'TV' }, { name: 'Taiwan - Province of China', iso2: 'TW' }, { name: 'Tanzania', iso2: 'TZ' }, { name: 'Ukraine', iso2: 'UA' }, { name: 'Uganda', iso2: 'UG' }, { name: 'Us Minor Outlying Islands', iso2: 'UM' }, { name: 'United States', iso2: 'US' }, { name: 'Uruguay', iso2: 'UY' }, { name: 'Uzbekistan', iso2: 'UZ' }, { name: 'Holy See (Vatican City State)', iso2: 'VA' }, { name: 'Saint Vincent', iso2: 'VC' }, { name: 'Venezuela', iso2: 'VE' }, { name: 'British Virgin Islands', iso2: 'VG' }, { name: 'Us Virgin Islands', iso2: 'VI' }, { name: 'Vietnam', iso2: 'VN' }, { name: 'Vanuatu', iso2: 'VU' }, { name: 'Wallis and Futuna Islands', iso2: 'WF' }, { name: 'Samoa', iso2: 'WS' }, { name: 'Yemen', iso2: 'YE' }, { name: 'Mayotte', iso2: 'YT' }, { name: 'Yugoslavia', iso2: 'YU' }, { name: 'South Africa', iso2: 'ZA' },
                        { name: 'Zambia', iso2: 'ZM' }, { name: 'Zimbabwe', iso2: 'ZW' }];
                }
            }
        });

        return service;
    };
})();