using System;

namespace SaaS.Api.Test.Models.Api.Oauth
{
    public class SessionViewModel
    {
        public Guid? MachineId { get; set; }
        public string MotherboardID { get; set; }
        public string PhysicalMAC { get; set; }
        public bool IsAutogeneratedMachineKey { get; set; }
        public string OsVersion { get; set; }
        public string PcName { get; set; }
    }
}