//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaaS.Mailer.Templates.LuluSoft.App_LocalResources.WelcomePurchaseMigrationFromSuiteNotification
{
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WelcomePurchaseMigrationFromSuiteNotification
    {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WelcomePurchaseMigrationFromSuiteNotification() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SaaS.Mailer.Templates.LuluSoft.App_LocalResources.WelcomePurchaseMigrationFromSuiteNotification" +
                            ".WelcomePurchaseMigrationFromSuiteNotification", typeof(WelcomePurchaseMigrationFromSuiteNotification).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The PDF Software you’ve always wanted.
        /// </summary>
        public static string Prgh_
        {
            get
            {
                return ResourceManager.GetString("Prgh_", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Congratulations! Your PDF Suite license will be switched over to Soda PDF, our most powerful PDF tool. Soda PDF was designed from the ground up with connectivity in mind. Whether at the office or home, access Soda PDF on the fly, from any device..
        /// </summary>
        public static string Prgh_1
        {
            get
            {
                return ResourceManager.GetString("Prgh_1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to With its unique technology, working offline and online on your PDF documents has never been easier with Soda PDF.  When it comes to quick things such as convert, edit, merge, electronic signatures and much more, Soda PDF will do it all in a flash..
        /// </summary>
        public static string Prgh_2
        {
            get
            {
                return ResourceManager.GetString("Prgh_2", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You’re one step away from all of these great features. For any help you need along the way, you can click here to contact our support team.
        ///
        /// </summary>
        public static string Prgh_3
        {
            get
            {
                return ResourceManager.GetString("Prgh_3", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to If you have a Soda PDF account, please login to your account to access your product.
        ///
        /// </summary>
        public static string Prgh_3_0
        {
            get
            {
                return ResourceManager.GetString("Prgh_3_0", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to Choose your password
        /// </summary>
        public static string Prgh_3_1
        {
            get
            {
                return ResourceManager.GetString("Prgh_3_1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Download and install Soda PDF
        /// </summary>
        public static string Prgh_3_2
        {
            get
            {
                return ResourceManager.GetString("Prgh_3_2", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Log into your brand new Soda PDF account
        /// </summary>
        public static string Prgh_3_3
        {
            get
            {
                return ResourceManager.GetString("Prgh_3_3", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You will receive your invoice in the next 24-72hrs.
        /// </summary>
        public static string Prgh_4
        {
            get
            {
                return ResourceManager.GetString("Prgh_4", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Learn more about Soda PDF by checking out our knowledge base, containing 100+ articles with the best tips and tricks to make the most out of the app..
        /// </summary>
        public static string Prgh_5
        {
            get
            {
                return ResourceManager.GetString("Prgh_5", resourceCulture);
            }
        }
    }
}

