//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaaS.Mailer.Templates.PdfForge.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class General {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal General() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SaaS.Mailer.Templates.PdfForge.App_GlobalResources.General", typeof(General).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All rights reserved.
        /// </summary>
        public static string allRightsReserved {
            get {
                return ResourceManager.GetString("allRightsReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is an automated message – do not reply to the sender. If you wish to reply to this email, please contact our.
        /// </summary>
        public static string automatedMsg {
            get {
                return ResourceManager.GetString("automatedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to customer support.
        /// </summary>
        public static string customerSupport {
            get {
                return ResourceManager.GetString("customerSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear.
        /// </summary>
        public static string Dear {
            get {
                return ResourceManager.GetString("Dear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to here.
        /// </summary>
        public static string here {
            get {
                return ResourceManager.GetString("here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Account.
        /// </summary>
        public static string myAccount {
            get {
                return ResourceManager.GetString("myAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been invited to use.
        /// </summary>
        public static string Prgh_1 {
            get {
                return ResourceManager.GetString("Prgh_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to install our PDF Architect 5 application..
        /// </summary>
        public static string Prgh_3 {
            get {
                return ResourceManager.GetString("Prgh_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use our knowledge base to learn more about how to .
        /// </summary>
        public static string Prgh_4 {
            get {
                return ResourceManager.GetString("Prgh_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you haven&apos;t downloaded PDF Architect 5 yet, you can get it .
        /// </summary>
        public static string Prgh_notDownloaded {
            get {
                return ResourceManager.GetString("Prgh_notDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string privacyPolicy {
            get {
                return ResourceManager.GetString("privacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regards,.
        /// </summary>
        public static string regards {
            get {
                return ResourceManager.GetString("regards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to reset your password.
        /// </summary>
        public static string resetPassword {
            get {
                return ResourceManager.GetString("resetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you.
        /// </summary>
        public static string ThankYou {
            get {
                return ResourceManager.GetString("ThankYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re very excited to have you on board!.
        /// </summary>
        public static string Welcome_Prgh_1 {
            get {
                return ResourceManager.GetString("Welcome_Prgh_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To unlock these amazing features and more, you must first create a password for your PDF Architect 5 account..
        /// </summary>
        public static string Welcome_Prgh_2 {
            get {
                return ResourceManager.GetString("Welcome_Prgh_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to create your password now.
        /// </summary>
        public static string Welcome_Prgh_3 {
            get {
                return ResourceManager.GetString("Welcome_Prgh_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your PDF Architect Team.
        /// </summary>
        public static string yourTeam {
            get {
                return ResourceManager.GetString("yourTeam", resourceCulture);
            }
        }
    }
}
