//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaaS.Mailer.Templates.LuluSoft.App_LocalResources.eSignEmailConfirmationNotification {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class eSignEmailConfirmationNotification {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal eSignEmailConfirmationNotification() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SaaS.Mailer.Templates.LuluSoft.App_LocalResources.eSignEmailConfirmationNotificat" +
                            "ion.eSignEmailConfirmationNotification", typeof(eSignEmailConfirmationNotification).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for using &lt;b&gt;Soda&lt;/b&gt; E-Sign!.
        /// </summary>
        public static string Prgh_1 {
            get {
                return ResourceManager.GetString("Prgh_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We just wanted to let you know that you can track the status and progress of your E-sign package. But first we need you to verify your account by clicking the button below:.
        /// </summary>
        public static string Prgh_2 {
            get {
                return ResourceManager.GetString("Prgh_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After you verify your account just click here to see your E-sign inbox where all your E-sign package progress is kept.
        ///
        ///Have any questions? Check out our &lt;a href=&quot;{0}&quot; style=&quot;font:16px/24px Arial; color:#3a74e6; text-decoration: underline;&quot;&gt;knowledge base&lt;/a&gt;..
        /// </summary>
        public static string Prgh_3 {
            get {
                return ResourceManager.GetString("Prgh_3", resourceCulture);
            }
        }
    }
}
