//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaaS.Mailer.Templates.LuluSoft.App_LocalResources.EmailChangeConfirmationNotification {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EmailChangeConfirmationNotification {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmailChangeConfirmationNotification() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SaaS.Mailer.Templates.LuluSoft.App_LocalResources.EmailChangeConfirmationNotifica" +
                            "tion.EmailChangeConfirmationNotification", typeof(EmailChangeConfirmationNotification).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to validate your new email.
        /// </summary>
        public static string Btn {
            get {
                return ResourceManager.GetString("Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have recently requested to change the email address associated with your Soda PDF account. Click on the validation link below to confirm the change..
        /// </summary>
        public static string Prgh_1 {
            get {
                return ResourceManager.GetString("Prgh_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once the email change is confirmed, you must only use your new email and current password to log in. Please note that if you have a product that was assigned to you by another user, the product will be assigned back to them..
        /// </summary>
        public static string Prgh_3 {
            get {
                return ResourceManager.GetString("Prgh_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any future communication related to your account will be sent to this email address..
        /// </summary>
        public static string Prgh_4 {
            get {
                return ResourceManager.GetString("Prgh_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you did not request these changes, please ignore this email..
        /// </summary>
        public static string Prgh_5 {
            get {
                return ResourceManager.GetString("Prgh_5", resourceCulture);
            }
        }
    }
}
