using Newtonsoft.Json;
using SaaS.Data.Entities.Accounts;
using System;

namespace SaaS.Api.Models.Oauth
{
    public class SignInViewModel
    {
        public SignInViewModel() { }

        public SignInViewModel(Account user, string grantType = "password", string clientId = "web")
        {
            GrantType = grantType;
            ClientId = clientId;

            SetUser(user);
        }

        [JsonProperty("grant_type")]
        public string GrantType { get; set; }

        public string UserName { get; set; }
        public string Password { get; set; }

        [JsonProperty("client_id")]
        public string ClientId { get; set; }

        [JsonProperty("client_version")]
        public string ClientVersion { get; set; }

        [JsonProperty("client_secret")]
        public string ClientSecret { get; set; }

        public Guid State { get; set; }
        public string Scope { get; set; }
        public Guid? InstallationID { get; set; }

        public void SetUser(Account user)
        {
            UserName = user.Email;
            Password = user.Password;
        }

        public string MotherboardKey { get; set; }
        public string PhysicalMac { get; set; }
        public string MachineKey { get; set; }
        public string PcName { get; set; }
        public bool IsAutogeneratedMachineKey { get; set; }
        public string ExternalClient { get; set; }
    }
}
