using System;
using System.Data.SqlClient;
using System.Threading.Tasks;

namespace SaaS.Identity
{
    public partial class AuthDbContext
    {
        internal async Task<Data.Entities.Oauth.OauthSystem> SystemInsertAsync(Data.Entities.Oauth.OauthSystem system)
        {
            var sqlParams = new SqlParameter[]
            {
                system.MachineKey.ToSql("machineKey"),
                system.MotherboardKey.ToSql("motherboardKey"),
                system.PhysicalMac.ToSql("physicalMAC"),
                system.IsAutogeneratedMachineKey.ToSql("isAutogeneratedMachineKey"),
                system.PcName.ToSql("pcName")
            };

            return await ExecuteReaderAsync<Data.Entities.Oauth.OauthSystem>("[oauth].[pSystemInsert]", sqlParams);
        }
    }
}