//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaaS.Mailer.Templates.LuluSoft.App_LocalResources.EmailChangeNotification {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EmailChangeNotification {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmailChangeNotification() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SaaS.Mailer.Templates.LuluSoft.App_LocalResources.EmailChangeNotification.EmailCh" +
                            "angeNotification", typeof(EmailChangeNotification).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please note that the email associated with your Soda PDF account has been successfully changed to.
        /// </summary>
        public static string Prgh_1_1 {
            get {
                return ResourceManager.GetString("Prgh_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to . Moving forward, your new email address must be used to log in..
        /// </summary>
        public static string Prgh_1_2 {
            get {
                return ResourceManager.GetString("Prgh_1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you did not request this change, please log in using the new email address, change your password immediately, and change the email on file to the correct one..
        /// </summary>
        public static string Prgh_2 {
            get {
                return ResourceManager.GetString("Prgh_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you need any help, you can create a ticket for our &lt;a href=&quot;https://sodapdf.desk.com/customer/en/portal/emails/new?ticket[labels_new]=account%20management&quot;&gt;support team&lt;/a&gt;..
        /// </summary>
        public static string Prgh_3 {
            get {
                return ResourceManager.GetString("Prgh_3", resourceCulture);
            }
        }
    }
}
