//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaaS.Mailer.Templates.LuluSoft.App_LocalResources.OSSunset {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OSSunset {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OSSunset() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SaaS.Mailer.Templates.LuluSoft.App_LocalResources.OSSunset.OSSunset", typeof(OSSunset).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best regards,.
        /// </summary>
        public static string Best_regards {
            get {
                return ResourceManager.GetString("Best_regards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;d like to inform you that our Online Services platform has been permanently shut down as of February 21st, 2018..
        /// </summary>
        public static string Prgh_1 {
            get {
                return ResourceManager.GetString("Prgh_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Online Services website has already been removed, so please retrieve your files using your Soda PDF application. Previous versions can be found &lt;a href=&quot;https://www.sodapdf.com/pdf-download/&quot; style=&quot;font:16px/24px Arial; color:#3a74e6; text-decoration: underline;&quot;&gt;here&lt;/a&gt;..
        /// </summary>
        public static string Prgh_2 {
            get {
                return ResourceManager.GetString("Prgh_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most users have already switched to our flagship product, Soda PDF Anywhere. Paid users have received free Soda PDF Home plans, while everyone can still access their features through both &lt;a href=&quot;https://online.sodapdf.com&quot; style=&quot;font:16px/24px Arial; color:#3a74e6; text-decoration: underline;&quot;&gt;Soda PDF Online&lt;/a&gt; and &lt;a href=&quot;https://www.sodapdf.com/pdf-download/&quot; style=&quot;font:16px/24px Arial; color:#3a74e6; text-decoration: underline;&quot;&gt;Soda PDF Desktop&lt;/a&gt;..
        /// </summary>
        public static string Prgh_3 {
            get {
                return ResourceManager.GetString("Prgh_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have any questions, feel free to contact our &lt;a href=&quot;https://sodapdf.desk.com/customer/en/portal/emails/new?ticket&quot; style=&quot;font:16px/24px Arial; color:#3a74e6; text-decoration: underline;&quot;&gt;support team&lt;/a&gt;..
        /// </summary>
        public static string Prgh_4 {
            get {
                return ResourceManager.GetString("Prgh_4", resourceCulture);
            }
        }
    }
}
