//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaaS.Mailer.Templates.LuluSoft.App_LocalResources.PolicyUpdateNotification {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PolicyUpdateNotification {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PolicyUpdateNotification() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SaaS.Mailer.Templates.LuluSoft.App_LocalResources.PolicyUpdateNotification.Policy" +
                            "UpdateNotification", typeof(PolicyUpdateNotification).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms of Use and End User License Agreement now reflect the fact that you can use both the desktop application as well as the online services (Soda PDF Online), including the free online converters.
        /// </summary>
        public static string list_1 {
            get {
                return ResourceManager.GetString("list_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policies now clarify the use of personal and product usage data since the majority of our users must now create an account instead of using a license key.
        /// </summary>
        public static string list_2 {
            get {
                return ResourceManager.GetString("list_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details added about the use of cookies, storage of information, and more.
        /// </summary>
        public static string list_3 {
            get {
                return ResourceManager.GetString("list_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We’ve recently updated our Privacy Policy, Terms of Use, and End User License Agreement to reflect the changes introduced with the launch of our latest product, Soda PDF Anywhere, and our online application, Soda PDF Online..
        /// </summary>
        public static string Prgh_1 {
            get {
                return ResourceManager.GetString("Prgh_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here are some of the important updates:.
        /// </summary>
        public static string Prgh_2 {
            get {
                return ResourceManager.GetString("Prgh_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The protection of your personal information and the transparency in the way we do business with you is of utmost importance to us. As always, Soda PDF is a participant of.
        /// </summary>
        public static string Prgh_3_sub1 {
            get {
                return ResourceManager.GetString("Prgh_3_sub1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to privacy certification program that enforces strong privacy management practices and safeguards your data..
        /// </summary>
        public static string Prgh_3_sub2 {
            get {
                return ResourceManager.GetString("Prgh_3_sub2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We encourage you to read our.
        /// </summary>
        public static string Prgh_4_sub1 {
            get {
                return ResourceManager.GetString("Prgh_4_sub1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in full..
        /// </summary>
        public static string Prgh_4_sub2 {
            get {
                return ResourceManager.GetString("Prgh_4_sub2", resourceCulture);
            }
        }
    }
}
