//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaaS.Mailer.Templates.LuluSoft.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Buttons {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Buttons() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SaaS.Mailer.Templates.LuluSoft.App_GlobalResources.Buttons", typeof(Buttons).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please click here to change your password.
        /// </summary>
        public static string ClickChangePasw {
            get {
                return ResourceManager.GetString("ClickChangePasw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here.
        /// </summary>
        public static string ClickHere {
            get {
                return ResourceManager.GetString("ClickHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to reset your password.
        /// </summary>
        public static string ClickResetPasw {
            get {
                return ResourceManager.GetString("ClickResetPasw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Password.
        /// </summary>
        public static string CreatePassword {
            get {
                return ResourceManager.GetString("CreatePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating Your Password.
        /// </summary>
        public static string CreatingYourPasw {
            get {
                return ResourceManager.GetString("CreatingYourPasw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create your password now.
        /// </summary>
        public static string CreatingYourPaswNow {
            get {
                return ResourceManager.GetString("CreatingYourPaswNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download the Desktop app.
        /// </summary>
        public static string DownloadDeskApp {
            get {
                return ResourceManager.GetString("DownloadDeskApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Inbox.
        /// </summary>
        public static string GotoInbox {
            get {
                return ResourceManager.GetString("GotoInbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to My Account.
        /// </summary>
        public static string GotoMyAccount {
            get {
                return ResourceManager.GetString("GotoMyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to modify your plan.
        /// </summary>
        public static string ModifyYourPlan {
            get {
                return ResourceManager.GetString("ModifyYourPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products and Pricing.
        /// </summary>
        public static string ProductsPricing {
            get {
                return ResourceManager.GetString("ProductsPricing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to products section in your account.
        /// </summary>
        public static string ProductsSectionYourAccount {
            get {
                return ResourceManager.GetString("ProductsSectionYourAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIGN IN.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to switch products.
        /// </summary>
        public static string SwitchProduct {
            get {
                return ResourceManager.GetString("SwitchProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try Soda PDF Online.
        /// </summary>
        public static string TryOnlineApp {
            get {
                return ResourceManager.GetString("TryOnlineApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify My Account.
        /// </summary>
        public static string VerifyMyAccount {
            get {
                return ResourceManager.GetString("VerifyMyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or visit the Online app.
        /// </summary>
        public static string VisitOnlineApp {
            get {
                return ResourceManager.GetString("VisitOnlineApp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Choose my password.
        /// </summary>
        public static string ChooseMyPassword
        {
            get
            {
                return ResourceManager.GetString("ChooseMyPassword", resourceCulture);
            }
        }
    }
}
